### ISSUE TITLE
Crear pregunta para cada curso correspondiente [Vista docente]

### ISSUE THREAD

**Issue by MiguelGonzalezAravena** [MiguelGonzalezAravena/TeclerasVirtualesPHP#20]
# Descripción

Crear vista y controlador correspondiente, que nos permita crear la preguntas. Debe contar con una opción para el tipo de pregunta que se desea crear, existen tres tipos de preguntas:
- Pregunta de alternativa.
- Pregunta dicotómica
- Pregunta escala de Likert.
# Flujo de trabajo
- [ ] Implementación: @Aaronponce, @Cleoz21, @olivarespablo
- [ ] Testing: [Por definir por el grupo]
- [ ] Merge request / Pull request: @MiguelGonzalezAravena, @DanielSilvaN

**Comment by rvelasquezrojas** [comment]
Las preguntas pueden contener archivos multimedia, en ninguna parte se describe esto, de hecho en ninguna parte se describen los campos de esta pregunta.
